[General]
DefaultFolder=/home/phil/Qsync
Language=en_us
NotShowQuickStart=true
ShowOverlayPathList=/home/phil/Qsync

[ConnectionInfo]
1\LinkInfo\AutoConnect=true
1\LinkInfo\DefaultIPAddress=192.168.1.203
1\LinkInfo\Enabled=true
1\LinkInfo\IPAddress=192.168.1.203
1\LinkInfo\LocalUserID=a35a288bdf361c03df550a70a18b85bbce381066
1\LinkInfo\MACAddress=245ebe62b4d8
1\LinkInfo\NASInfo\Address1="192.168.1.203,1,1"
1\LinkInfo\NASInfo\Address2="ts-264,1,6"
1\LinkInfo\NASInfo\Address3="phil264.myqnapcloud.com,2,3"
1\LinkInfo\NASInfo\Address4="79.71.73.148,2,2"
1\LinkInfo\NASInfo\AddressNUM=4
1\LinkInfo\NASInfo\ExternalHttpPort=8080
1\LinkInfo\NASInfo\ExternalHttpsPort=443
1\LinkInfo\NASInfo\InternalHttpPort=8080
1\LinkInfo\NASInfo\InternalHttpsPort=443
1\LinkInfo\NasCUID=9c19b3ece9ab8c564862bcd27863c201
1\LinkInfo\NasID=52864165f3dbbe4f165a1f184f44a612
1\LinkInfo\NasSUID=3acf7b7fd970fd5e3cc289c21b0ab51f
1\LinkInfo\NasUserCUID=14381164923ae0deea53e1d80a4f4d77
1\LinkInfo\PCName=daffy
1\LinkInfo\Password=@ByteArray(bWFyazN0YVBC)
1\LinkInfo\Port=8080
1\LinkInfo\QToken="@ByteArray(ZmEzMDJjMmRkY2U0NDhhOGIyYzM1OGU4NDA3ZDU4M2E=)"
1\LinkInfo\SecureConnect=false
1\LinkInfo\ServerName=ts-264
1\LinkInfo\UserName=phil
1\ProcessedMaxConfigLogIdx64=0
1\ProcessedMaxGlobalNotifyLogIdx64=14
1\ProcessedMaxNotifyLogIdx64=0
1\Settings\Mail\AuthEnable=true
1\Settings\Mail\AuthUserName=
1\Settings\Mail\AuthUserPassword=@ByteArray()
1\Settings\Mail\NasSentEmail=0
1\Settings\Mail\SMTPPort=0
1\Settings\Mail\SMTPServer=
1\Settings\Mail\SecureEnable=false
1\Settings\Mail\SecureType=2
1\Settings\Mail\SenderAddress=
1\Settings\Mode\SyncModeType=1
1\Settings\Policy\ConflictPolicy=5
1\Settings\Policy\FileFilterPolicy=*.~*\t*.!BW!\t~*.*\t#*.*\t*.part*\tthumbs.db\t*.crdownload\t.*\t*.tmp\t*.temp\t*.pst\t*.ost
1\Settings\SetNASConfig=true
1\Settings\SetNASConfigFlags=0
1\ShareLinkAddr=192.168.1.203
1\ShareLinkAddrType=1
1\ShareLinkUseSSL=false

[FolderPairInfo]
1\ConnectionID=1
1\Enable=true
1\MonitoredPath=/home/phil/Qsync
1\Privilege=2
1\ProcessedMaxLogIdx64=3
1\ShareFolderAlias=/home/.Qsync
1\ShareFolderFullPath=/share/homes/phil/.Qsync
1\ShareFolderPath=/home/.Qsync
1\SyncInfoPath=/home/phil/.local/share/QNAP/Qsync/FolderPairs/1
1\SyncStatus=true

[Settings]
Mode\Region=1
Proxy\AutoProxyAuth=false
Proxy\AutoProxyPassword=@ByteArray()
Proxy\AutoProxyPort=3128
Proxy\AutoProxyServer=
Proxy\AutoProxyUsername=
Proxy\Mode=0
